/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type MediaKind = "movie" | "tv";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TitleSource = "catalog" | "tmdb";

export interface MemberChoices {
  memberId: string;
  stars: number | null;
  status: string;
  titleId: string;
  updatedAt: Generated<Timestamp>;
}

export interface MemberPrefs {
  decades: Generated<number[]>;
  genreKeys: Generated<string[]>;
  kind: string;
  memberId: string;
  roomId: string;
  updatedAt: Generated<Timestamp>;
}

export interface RoomMembers {
  createdAt: Generated<Timestamp>;
  displayName: string;
  id: string;
  roomId: string;
}

export interface RoomPicks {
  createdAt: Generated<Timestamp>;
  memberId: string;
  roomId: string;
  titleId: string;
}

export interface Rooms {
  code: string;
  createdAt: Generated<Timestamp>;
  id: string;
  name: Generated<string>;
}

export interface SearchQueries {
  createdAt: Generated<Timestamp>;
  hitCount: Generated<number>;
  lastHitAt: Generated<Timestamp>;
  query: string;
}

export interface Titles {
  backdropPath: string | null;
  createdAt: Generated<Timestamp>;
  genres: string | null;
  id: string;
  kind: MediaKind;
  name: string;
  overview: Generated<string>;
  posterPath: string | null;
  source: Generated<TitleSource>;
  trailerKey: string | null;
  year: number;
}

export interface DB {
  memberChoices: MemberChoices;
  memberPrefs: MemberPrefs;
  roomMembers: RoomMembers;
  roomPicks: RoomPicks;
  rooms: Rooms;
  searchQueries: SearchQueries;
  titles: Titles;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const MediaKindArrayValues: [MediaKind, ...MediaKind[]] = ["movie","tv"];
export const TitleSourceArrayValues: [TitleSource, ...TitleSource[]] = ["catalog","tmdb"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
